[toolchain]

[workspace]
types = "src/idl/"

[features]
seeds = false
skip-lint = false

[programs.localnet]
owned_counter = "ENdp1djfauQdhWivbq9eWccodFhepPgk35YhbU6vN5NV"
shared_counter = "6Zxr95zDqagjfR5JAdZ24dT3FTqzn5N2eaagGHXEbA22"

[programs.devnet]
owned_counter = "4VaxisFFjxbjD6gNDBjid7gaptQvNp1tpRTgGS5YfC22"
shared_counter = "5v1W7sNkrufDdRND19rxtMWmLXEXWbwTRy4mq7Dk3B6m"

[programs.testnet]
owned_counter = "4VaxisFFjxbjD6gNDBjid7gaptQvNp1tpRTgGS5YfC22"
shared_counter = "5v1W7sNkrufDdRND19rxtMWmLXEXWbwTRy4mq7Dk3B6m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

